baseURL = 'https://acebase.cc/'
languageCode = 'en-us'
title = 'AceBase | Ace玩家基地'
theme = 'pehtheme-hugo'
[[menu.main]]
    name = "所有文章"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "标签分类"
    url = "/tags/"
    weight = 2